stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/front-babyhelm/babyhelm"

build:
  stage: build
  image: docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  services:
    - docker:dind
  script:
    - docker info
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image:
    name: alpine/helm
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - helm upgrade --install babyhelm-front babyhelm-front --namespace=babyhelm --kubeconfig $DEV_CLUSTER_KUBECONFIG

mirror:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - git config --global user.email "babyhelm@gmail.com"
    - git config --global user.name "ci-babyhelm"
    - git remote add github "https://$GITHUB_TOKEN@github.com/IU-Capstone-Project-2024/babyhelm-front.git"
    - git push --mirror github