apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.service.postfix }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.service.type }}
  loadBalancerClass: {{ .Values.app.service.loadBalancerClass }}
  ports:
    - port: {{ .Values.app.service.ports.port }}
      targetPort: {{ .Values.app.service.ports.targetPort }}
  selector:
    app: {{ .Values.app.name }}