app:
  name: front

  replicas: 2

  deployment:
    postfix: deployment
    image: registry.gitlab.com/front-babyhelm/babyhelm:latest
    port: 80

  service:
    postfix: svc
    type: LoadBalancer
    loadBalancerClass: tailscale
    ports:
      port: 80
      targetPort: 80
